"""Inference FinOps: route each task to the cheapest model that can do it, and
serve repeat questions from a semantic cache instead of paying for them twice.

Two mechanisms, both from the doc's §7.4 "Inference FinOps Semantic Router,"
adapted to this project's free/open-weights stack (small Llama vs 70B Llama,
not FinBloom-7B vs GPT-4o):

  1. Tiered routing. Cheap, mechanical tasks (planning the brief, the yes/no
     compliance judge) go to a small model; the tasks that need real writing
     (draft, revise) go to the large one. `tier_for(task)` is the policy.

  2. Semantic cache. The same advisor often asks the same thing. We embed the
     (client, question) with the on-device MiniLM model the vector store already
     uses — no API key — and if a new question is semantically close to one we've
     answered for that client under the same guardrail setting, we return the
     stored result: zero tokens, sub-millisecond.

`estimate_cost()` turns a per-call usage meter into an illustrative dollar
figure. The rates are placeholders in the shape of hosted open-weights pricing,
labeled as such; the point is that cost becomes *measurable*, not that these are
TIFIN's real numbers.
"""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

import chromadb

import llm

DATA = Path(__file__).parent / "data"
CACHE_COLLECTION = "qcache"

# how close (cosine) a new question must be to a cached one to count as a hit
SIMILARITY_THRESHOLD = 0.92

# which model tier each agent task runs on
_TASK_TIER = {
    "plan": "small",
    "judge": "small",
    "draft": "large",
    "revise": "large",
}

# illustrative hosted open-weights rates, USD per 1M tokens (input, output).
# NOT TIFIN's real pricing — here so cost is measurable, not exact.
_RATES = {
    "small": {"in": 0.05, "out": 0.08},
    "large": {"in": 0.59, "out": 0.79},
}


def tier_for(task: str) -> str:
    """Map an agent task to its model tier. Unknown tasks default to large."""
    return _TASK_TIER.get(task, "large")


def estimate_cost(meter: list[dict]) -> float:
    """Sum an illustrative dollar cost across a list of per-call usage dicts.

    Each dict looks like {"tier","model","in","out"}. Returns USD, 6 dp."""
    total = 0.0
    for call in meter:
        rate = _RATES.get(call.get("tier", "large"), _RATES["large"])
        total += call.get("in", 0) / 1e6 * rate["in"]
        total += call.get("out", 0) / 1e6 * rate["out"]
    return round(total, 6)


@lru_cache(maxsize=1)
def _cache_collection():
    client = chromadb.PersistentClient(path=str(DATA / "chroma"))
    # built-in on-device MiniLM embedding (same as the filings store) — no API key
    return client.get_or_create_collection(CACHE_COLLECTION, metadata={"hnsw:space": "cosine"})


def _key(client_id: str, question: str) -> str:
    return f"[{client_id}] {question.strip()}"


def cache_get(client_id: str, question: str, enforce: bool) -> dict | None:
    """Return a cached AskResult dict for a semantically-matching prior question,
    scoped to the same client, guardrail setting, and provider. None on miss.

    Scoping by provider matters: an answer generated by local Ollama must not be
    served later when the app is pointed at Groq."""
    col = _cache_collection()
    try:
        res = col.query(
            query_texts=[_key(client_id, question)],
            n_results=1,
            where={"$and": [{"client_id": client_id}, {"enforce": enforce},
                            {"provider": llm.provider()}]},
        )
    except Exception:
        return None
    docs = res.get("documents") or [[]]
    if not docs or not docs[0]:
        return None
    distance = res["distances"][0][0]
    if (1.0 - distance) < SIMILARITY_THRESHOLD:  # cosine distance -> similarity
        return None
    payload = res["metadatas"][0][0].get("result")
    return json.loads(payload) if payload else None


def cache_put(client_id: str, question: str, enforce: bool, result: dict) -> None:
    """Store an AskResult dict keyed by the (client, question, guardrail) tuple."""
    col = _cache_collection()
    provider = llm.provider()
    cid = f"{client_id}|{int(enforce)}|{provider}|{abs(hash(question.strip()))}"
    try:
        col.upsert(
            ids=[cid],
            documents=[_key(client_id, question)],
            metadatas=[{"client_id": client_id, "enforce": enforce, "provider": provider,
                        "result": json.dumps(result)}],
        )
    except Exception:
        pass  # a cache write failure must never break a live request
